"""add followers

Revision ID: 55209c9a70ce
Revises: b273db529eb6
Create Date: 2024-01-16 22:20:19.150278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55209c9a70ce'
down_revision = 'b273db529eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
