"""add filename string

Revision ID: 5d46b7367405
Revises: 5dd55f4a80e4
Create Date: 2024-02-18 02:55:19.224929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d46b7367405'
down_revision = '5dd55f4a80e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_files_name', sa.String(length=140), nullable=True))
        batch_op.drop_column('total_photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_photo', sa.INTEGER(), nullable=True))
        batch_op.drop_column('all_files_name')

    # ### end Alembic commands ###
