"""add new columns for user

Revision ID: b273db529eb6
Revises: b1077aa9d8b8
Create Date: 2024-01-15 00:36:58.339801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b273db529eb6'
down_revision = 'b1077aa9d8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('create_time')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
